admin_user: ENC[AES256_GCM,data:c0W41UzFxw==,iv:N4lhsNJwCi/7NJ/6XKXXrAo8PO3FOaDZm8smytB8t0A=,tag:8pqhWE7XRl59P4kyY1IHeg==,type:str]
admin_password: ENC[AES256_GCM,data:LZOUWrQ/yg2bLsTIdYMMscE=,iv:umBe7VR3ffcQJBGQbHdg1/J3NhC3kLOtgunNUAIkwZM=,tag:23LALjNChLs+s1ZA2ohU2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-23T12:26:22Z"
    mac: ENC[AES256_GCM,data:RjZPPCaROi+c1H0JtPaqN0x31R/uhiPuWsGCeFb8EB7Jqim+9o2tytIdma1UIBLr5iJrWTpxJsnWBnaCwf5B/kOPNhw61oL/8rIZdVH+bU5kiWJ4t/yz7ifATlD4fXGvFt19Om/lyklj8jIUNH4F/NaHmKmYpmluGLnxMYDduLI=,iv:FM6Ef/5exC88oSzakJdstbcaxwv2ZkADmBIc70zXNaU=,tag:yR6PwSEJgxPWAsBe7ZR2lg==,type:str]
    pgp:
        - created_at: "2022-08-23T12:26:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxhfkHuNHvXMAQv/ahyVVCRGrvZDvNLf8pckxaDhoD5UJDUhQg5/BEy2KYF7
            czoiRAkSlitIyUavs7LJrxqxlaYZG5N+ezC77oHRLb4IqDeCmVPm/Z9mS7b+NpGY
            ZbYTXVGCrkvQKr9Bl+FhqRo39g3vNT7BC/mLQ1wT9cfDTsT9WWBRc10qPypJwhxz
            3SQTsRF7gqTdW34eHkL5S5F9BbLQU6VItmU35utwMOsn0v3qFVZFbeUjtC2OXGzh
            VEEBWPKW9g6YBjLAWdxHkxumAkfvYERHJoU71nhY0hflNt7s5exsEPvYicGNZh4E
            S0UIVgYixmLHdOe9jRakHyoqDZE2UJZh+2xoScAS3jioL5Z42SWzxxEyefu6IbGm
            uv7t5zV4Nc7gs5heU294vGdJ169CNfAtuzKTjq7+lm00Lx6tmzGDanoxifjGE99I
            cP6HKBaZ2Svnx/XqyxMIafX6/+F/P9ABYmtf1Lh2Qfkw2v2omgz0tyZOSUsMfvuK
            0MmQdJxBmLtR1p3ElVJF0l4B8MGfs6y2gjwJMexkT6EhHyY+fqsRXFwbSkWi7d+x
            Gk00QQVEkzLG+I3BwzZpnUdZHN5fUZKIkr4nietkee4TVX5xGD4Rsbj/vY5NpYd5
            xdA8a88l56tgUqK3y2Ro
            =MOEg
            -----END PGP MESSAGE-----
          fp: 20AB6E5725948E28F11E1D731D556C252EDB1676
    unencrypted_suffix: _unencrypted
    version: 3.7.3
