kind: Secret
apiVersion: v1
metadata:
  name: email-auth-secret
  namespace: monitoring
type: Opaque
stringData:
  auth-password: {{ .Values.encrypted_alertmanager_smtp_password | decryptAES (.Values.aesKey | b64dec) }}
