apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-node-rules
  namespace: {{ .Release.Namespace }}
  labels:
    role: alert-rules
    prometheus: prometheus-kube-prometheus-prometheus
spec:
  groups:
  - name: node.rules
    rules:
    - alert: HostOutOfMemory
      expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Host out of memory (instance {{ printf "{{ $labels.instance }}" }})
        description: "Node memory is filling up (< 10% left)\n  VALUE = {{ printf "{{ $value }}" }}\n   LABELS = {{ printf "{{ $labels }}" }}"
    - alert: HostOutOfDiskSpace
      expr: (node_filesystem_avail_bytes{fstype!~"tmpfs"} * 100) / node_filesystem_size_bytes{fstype!~"tmpfs"} < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Host out of disk space (instance {{ printf "{{ $labels.instance }}" }})
        description: Disk is almost full (< 10% left)
        value: "{{ printf "{{ $value }}" }}"
