kind: Secret
apiVersion: v1
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin_user: {{ .Values.sops_admin_user }}
  admin_password: {{ .Values.sops_admin_password }}
