namespace: monitoring
replicaCount: 1

image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  tag: "8.4.4"

app:
  grafana:
    encrypted_admin_user: uiMrMocL0CmmEy0sH1Ni9eeWeSpS/HieUIBELQAHWHk/AUi4bd1g9e6Yp54ldxeC
    encrypted_admin_password: hWeECYfpCL9kYu8DGeBu+uXZ5uDZPm7xSBFiTR/ShZU=

vhost:
  name: monitoring.leportail.org

pv:
  host_path: /mnt/k3s-data/grafana
