apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-le-portail
  labels:
    alertmanagerConfig: le-portail
spec:
  route:
    groupBy:
    - alertname
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 1h
    receiver: email
    routes:
    - match:
        alertname: EndpointDown
      receiver: email
    - match:
        alertname: HostOutOfMemory
      receiver: email
    - match:
        alertname: HostOutOfDiskSpace
      receiver: email
  receivers:
  - name: email
    emailConfigs:
    - to: guillaume.penaud@gmail.com
      from: cagette@leportail.org
      smarthost: smtp.mail.ovh.net:587
      authUsername: cagette@leportail.org
      authPassword:
        name: email-auth-secret
        key: auth-password
