{{- range $name, $cronjob := .Values.app.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $name }}
            image: {{ $cronjob.image_repository }}:{{ $cronjob.image_tag }}
            imagePullPolicy: IfNotPresent
            command: {{ $cronjob.command_arguments }}
          restartPolicy: OnFailure
{{- end }}
