nameOverride: ""
fullnameOverride: ""

app:
  # application configuration #
  # --------------------------#
  configuration:
    webapp:
      vhost: alterconso.leportail.org
      sql_log_enabled: false
      debug_enabled: true
      mailer_host: localhost
      mailer_port: 5000
      mysql_enabled: true
      mysql_user: docker
      mysql_password: docker
      mysql_host: localhost
      mysql_port: 3306
      mysql_database: db

  # cronjobs configuration #
  # -----------------------#
  cronjobs:
    opening-order:
      schedule: 0 9 * * MON
      image_repository: alterconso-mailer
      image_tag: 1.0.0
      command_arguments:
        - remind
        - --subject "Les commandes sont ouvertes"
        - --group-name "Alterconso du Val de Brenne"
        - --template-name "opening_order"
        - --template-address "alterconso.leportail.org"
        - --sender-mail "alterconso@leportail.org"
    closing-order:
      schedule: 0 9 * * THU
      image_repository: alterconso-mailer
      image_tag: 1.0.0
      command_arguments:
        - remind
        - --subject "Les commandes vont bientôt fermer"
        - --group-name "Alterconso du Val de Brenne"
        - --template-name "closing_order"
        - --template-address "alterconso.leportail.org"
        - --sender-mail "alterconso@leportail.org"

  # containers configuration #
  # -------------------------#
  containers:
    webapp:
      replicaCount: 1
      image:
        repository: alterconso-webapp
        pullPolicy: IfNotPresent
        tag: "1.0.0"
      imagePullSecrets: []
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi

    # Mailer configuration #
    # ---------------------#
    mailer:
      replicaCount: 1
      image:
        repository: alterconso-mailer
        pullPolicy: IfNotPresent
        tag: "1.0.0"
      imagePullSecrets: []
      ports:
        - name: mailer
          containerPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 150m
          memory: 64Mi
  serviceAccount:
    create: true
    name: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging-clusterissuer"
      cert-manager.io/issue-temporary-certificate: "true"
      acme.cert-manager.io/http01-edit-in-place: "true"
    hosts:
      - host: alterconso.leportail.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
        - alterconso.leportail.org
        secretName: alterconso.leportail.org-tls
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90

mysql:
  enabled: true
