apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-blackbox-rules
  namespace: monitoring
  labels:
    role: alert-rules
    prometheus: prometheus-kube-prometheus-prometheus
spec:
  groups:
  - name: blackbox.rules
    rules:
    - alert: EndpointDown
      expr: probe_success == 0
      for: 10s
      labels:
        severity: "critical"
      annotations:
        summary: "Your website {{ printf "{{ $labels.instance }}" }} is down"
