
- name: "Sources Webapp - clone alterconso-webapp repository on master branch"
  block:
  - name: "Git - tries to clone magento repository"
    ansible.builtin.git:
      repo: "https://github.com/gpenaud/alterconso-webapp.git"
      dest: "{{ webapp_project_path }}"
      
      version: "{{ webapp_repository_branch | default(webapp_default_branch) }}"
      force: "{% if force is defined and force == 'yes' %} true {% else %} false {% endif %}"
    register: out
    ignore_errors: true
  
  - name: "Sources Webapp - check if failure is authorized or not"
    fail:
      msg: "The clonage of the repository failed for a bad reason : {{ out.msg }}"
    when: "out.failed and 'Local modifications exist in the destination:' not in out.msg"

  - name: "Sources Webapp : copy apache2 and alterconso templates"
    ansible.builtin.template:
      src: templates/{{ template.src }}.j2
      dest: "{{ webapp_project_path }}/configuration/{{ template.dest }}"
      mode: 0644
    loop:
      - src: webapp/config.xml
        dest: app/config.xml
      - src: webapp/vhost.conf
        dest: apache2/vhosts/alterconso.conf
    loop_control:
      loop_var: template
  tags:
  - alterconso