kind: Deployment
apiVersion: apps/v1
metadata:
  name: external-dns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.11.0
        args:
        - --log-level=debug
        - --source=service
        - --source=ingress
        - --domain-filter=happynuts.me # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=scaleway
        env:
        - name: SCW_ACCESS_KEY
          value: "SCWFEX1135RCFRT8SBAC"
        - name: SCW_SECRET_KEY
          value: "6de830da-b1d8-4af0-b3c0-5d42478d0141"
