kind: Secret
apiVersion: v1
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.admin.encrypted_user | decryptAES (.Values.aesKey | b64dec)}}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.admin.encrypted_password | decryptAES (.Values.aesKey | b64dec)}}
