---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-grafana
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
              mountPath: /var/lib/grafana
            # global configuration
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            # datasource configuration
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
              subPath: datasource.prometheus
            # display dashboards
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
              mountPath: /etc/grafana/provisioning/dashboards/overview.yaml
              subPath: dashboards
            # import overview dashboards
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-overview
              mountPath: /var/lib/grafana/dashboards/overview/node-exporter.json
              subPath: node-exporter.json
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-overview
              mountPath: /var/lib/grafana/dashboards/overview/blackbox-exporter.json
              subPath: blackbox-exporter.json
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-overview
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap-overview
