- name: Base - Install basic components of VPS
  hosts: vps
  gather_facts: true
  tasks:

    - name: Base - install python3 package
      become: true
      ansible.builtin.raw: apt install python3
      register: apt_output
      changed_when: apt_output.rc == 0
      args:
        executable: /bin/bash
      tags:
        - python

    - name: Base - install docker-related packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - libcurl3t64-gnutls
        - libcurl4t64
      tags:
        - docker

    - name: Base - add docker's official GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Base - test docker's official GPG key
      ansible.builtin.apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Base - set up the stable apt docker repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
      tags:
        - docker

    - name: Base - install docker packages from apt sources
      become: true
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      loop_control:
        loop_var: package_name
      tags:
        - docker

    - name: Base - add ansible ssh user to "docker" group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: true
      tags:
        - docker

    - name: Base - install snapd for certbot
      become: true
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: true
      tags:
        - certbot

    - name: Base - install certbot through snap
      become: true
      community.general.snap:
        name:
          - certbot
        classic: true
      tags:
        - certbot
