version: "3.6"

services:
  webapp:
    image: gpenaud/alterconso-webapp
    build:
      context: ./../webapp
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../webapp/configuration/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./../webapp/configuration/apache2/certificates:/etc/apache2/certificates
      - ./../webapp/configuration/apache2/vhosts/https.conf:/etc/apache2/sites-available/alterconso.localhost.conf
      - ./../webapp/configuration/apache2/vhosts/https.conf:/etc/apache2/sites-enabled/alterconso.localhost.conf
      - ./../webapp/configuration/app/config.xml:/var/www/alterconso/config.xml
      # bound volumes for development
      - ./../webapp/app/src/controller/Cron.hx:/var/www/alterconso/src/controller/Cron.hx
      - ./../webapp/app/src/App.hx:/var/www/alterconso/src/App.hx
    depends_on:
      - mysql
    networks:
      - alterconso
