
- name: "Main : create monitoring project directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ grafana_path }}/dashboards"
    - "{{ grafana_path }}/datasources"
    - "{{ prometheus_path }}"
  tags:
    - monitoring

- name: "Main : copy docker-compose and .env templates"
  ansible.builtin.template:
    src: templates/{{ template }}.j2
    dest: "{{ project_path }}/{{ template }}"
    mode: 0644
  loop:
    - .env
    - docker-compose.yml
  loop_control:
    loop_var: template
  tags:
    - monitoring

- name: "Main : copy configuration templates"
  ansible.builtin.template:
    src: "templates/configuration/{{ template.source_dir }}/{{ template.file }}.j2"
    dest: "{{ project_path }}/{{ template.remote_dir }}/{{ template.file }}"
    mode: 0644
  loop:
    - source_dir: prometheus
      remote_dir: prometheus
      file: prometheus.yml
    - source_dir: grafana
      remote_dir: grafana
      file: grafana.ini
    - source_dir: grafana/datasources
      remote_dir: grafana/datasources
      file: datasources.yml
    - source_dir: grafana/dashboards
      remote_dir: grafana/dashboards
      file: dashboard.yml
    - source_dir: grafana/dashboards
      remote_dir: grafana/dashboards
      file: node.json
  loop_control:
    loop_var: template
  tags:
    - monitoring
    - current